name: Spider Jar Gen CI

on: workflow_dispatch

jobs:
  build:

    runs-on: windows-latest
    
    steps:
    - name: 检出分支代码
      uses: actions/checkout@v4
      with:
        ref: 20240917
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'
        cache: gradle
        
    - name: Build with Gradle
      run: ./buildAndGenJar.bat ec
        
    - name: Update spider jar
      uses: EndBug/add-and-commit@v7
      with:
        branch: 20240917
        default_author: github_actions
        message: 'update spider jar'
        add: "['./jar/custom_spider.jar', './jar/custom_spider.jar.md5']"
